// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "tutorial_des_1": "Beautify Your Home With \nThe Best Modular Switch From Litaski",
  "tutorial_des_2": "Redeem Earned Reward Points \nThrough Bank Transfer / Gift Cards",
  "pointsEarned": "Points Earned",
  "enterYourIssueHere": "Enter your issue here",
  "enterYourTicketIssue": "Enter your ticket issue ",
  "enterYourCommentHere": "Enter your comment here",
  "unauthorizedLogin": "Unauthorized Login",
  "youAreLoggedInAnotherDevice": "You are logged in another device",
  "YourAreLoggedOut": "Your are logged out",
  "ticketNumber": "Ticket Number",
  "ticketStatus": "Ticket Status",
  "kycWarningDialog": "After transferring points \nit is your responsibility to\n collect money from the dealer. \nSalesman / Other person is not\n responsible for payment",
  "resolved": "Resolved",
  "details": "Details",
  "resolvedOn": "Resolved On",
  "createdOn": "created On",
  "completeYourKyc": "Complete your KYC \nVerification",
  "KYCIsNotUpdateMessage": "kindly complete your KYC process. If submitted already contact support",
  "ticketTitle": "Ticket Title",
  "otherIssue": "Other Issue",
  "additionalPoint": "Additional Point",
  "basePoint": "Base Point",
  "qrCode": "Qr Code",
  "scannedDate": "Scanned Date",
  "open": "Open",
  "expiredDate": "Expired Date",
  "success": "success",
  "redeemedOn": "Redeemed On",
  "userProfile": "User Profile",
  "getKnowYourBetter": "Let's Get To Know You Better",
  "markedFieldsAreMandatory": "Marked fields are mandatory",
  "markedFieldAreMandatory": "Marked fields are mandatory",
  "emailID": "Email ID",
  "GetRewarded": "Get Rewarded",
  "Skip": "Skip",
  "create": "Create",
  "remoteConfigUpdateContent": "App features are changed, Please update the app",
  "mailSent": "Mail Sent",
  "scanAgain": "Scan Again",
  "enterYourCouponCode": "Enter your coupon code",
  "yourEmailHasBeenSentSuccessfully": "Your email has been sent successfully",
  "Redeem": "Redeem",
  "rateUs": "Rate Us",
  "LetsGo": "Let's Go",
  "goBack": "Go Back",
  "changeLanguage": "Change  Language",
  "cancel": "Cancel",
  "welcomeToLitaski": "Welcome!",
  "logout": "Logout",
  "yes": "Yes",
  "no": "No",
  "ok": "Ok",
  "retry": "Retry",
  "confirm": "Confirm",
  "active": "Active",
  "getOTP": "Get OTP",
  "send": "send",
  "update": "update",
  "enterCodeManually": "Enter Code Manually",
  "OTPVerification": "OTP \nVerification",
  "hasSendOTP": "OTP Has Been Sent To",
  "validate": "Verify",
  "didNotGetIt": "Didn't Get It? ",
  "getYouStarted": "Sign in to access your account",
  "enterYourMobileNo": "Enter your mobile no",
  "chooseLanguage": "Choose Language",
  "resendCode": "Resend Code",
  "hello": "Hello! {userName}",
  "whatsappURlAndroid": "whatsapp://send?{phoneNumber}&text={message}}",
  "whatsappURLIos": "https://wa.me/{phoneNumber}?text={Uri.parse({message})}",
  "scanHere": "Scan Here",
  "settings": "Settings",
  "yourWalletBalanceIs": "Wallet Balance",
  "redeemYourWalletPoints": "Redeem Your Wallet Points",
  "earnedQrCodes": "Earned QR Codes",
  "expiredQrCodes": "Expired QR Codes",
  "redeemedQrCodes": "Redeemed QR Codes",
  "verifiedQrCodes": "Verified QR Codes",
  "visitOurWebSite": "Visit Our WebSite",
  "howCanWeHelp": "How Can We Help?",
  "fillOutTheDetailsAndWeShallGetBackToYou": "Fill Out The Details And We Shall Get Back To You",
  "bankTransfer": "Bank Transfer",
  "tenpts": "10 Pts",
  "tabHere": "TAP HERE",
  "toScan": "TO SCAN",
  "home": "Home",
  "transactions": "Transactions",
  "profile": "Profile",
  "whatsapp": "WhatsApp",
  "proceedToChat": "Proceed To Chat",
  "manageBankAccounts": "Manage Bank Accounts",
  "languageSettings": "Language Settings",
  "contactUs": "Contact Us",
  "aboutUs": "About Us",
  "earned": "Earned",
  "redeemed": "Redeemed",
  "expired": "Expired",
  "verified": "Verified",
  "notifications": "Notifications",
  "couponDetails": "Coupon Details",
  "privacyPolicy": "Privacy Policy",
  "termsAndCondition": "Terms And Conditions",
  "support": "Support",
  "ticketDetails": "Ticket Details",
  "userName": "User Name*",
  "accountNo": "Acc No. :",
  "branch": "Branch :",
  "bankName": "Bank Name :",
  "bankNameHolder": "Bank Name",
  "branchNameHolder": "Branch Name",
  "branchName": "Indian Overseas Bank",
  "ifscCode": "IFSC Code :",
  "accountHolderName": "Account Holder Name",
  "accountNumber": "Account No.",
  "reEnterAccountNumber": "Re-enter Account No.",
  "doYouWantLogout": "Do You Want Logout?",
  "doYouWantDeleteAccount": "Do You Want Delete This Account?",
  "ifscCodeNumber": "IFSC Code",
  "indianBank": "Indian Bank",
  "goToHome": "Go To Home",
  "tNagar": "T Nagar",
  "add": "add",
  "emailId": "Email ID",
  "phoneNumber": "Phone Number",
  "addBankAccount": "Add Bank Account",
  "yourCouponCode": "    Your Coupon Code",
  "createTicket": "Create Ticket",
  "locationPermissionIsMandatoryToPerformScanOperation": "Location Permission is mandatory to perform Scan operation",
  "locationPermissionIsMandatoryToPerformBankTransferOperation": "Location Permission is mandatory to perform Bank Transfer operation",
  "goToSettings": "Go To Settings",
  "message": "Message",
  "aboutLitaski": "About Litaski",
  "aboutTheApp": "About The App",
  "sampymsf": "Sampymsf",
  "pleaseEnterCouponCodeManually": "Please Enter Coupon Code Manually",
  "Proceed": "Proceed",
  "openTickets": "Open Tickets",
  "allTickets": "All Tickets",
  "login": "Login",
  "delete": "Delete my account",
  "successful": "Successful",
  "congratulations": "Congratulations!",
  "failure": "Failure",
  "tryAgain": "Try Again",
  "youAreOffline": "You're offline",
  "noNotifications": "No Notifications",
  "created": "Created",
  "notFound": "Not Found",
  "reload": "Reload",
  "allow": "Allow",
  "selectPayee": "Select Payee",
  "transferAmount": "Transfer Amount",
  "remarks": "Remarks",
  "proceed": "Proceed",
  "enterTheVerificationOTP": "Enter the verification OTP",
  "kindlyEnterYourBankAccountDetailsToRedeemYourPoints": "Kindly enter your bank account details to\nredeem your points",
  "yourCouponPointsAddedIntoYourWalletSuccessfully ": "Your coupon points {points} added into your wallet successfully",
  "yourAreNotConnectedToTheInternetPleaseConnectAndTryAgain": "your are not connected to the internet.\nPlease connect and try again",
  "wellNotifyYouWhenSomethingArrived": "We'll notify you when something arrived",
  "unableToScan": "Unable to scan!",
  "bankAccountAdded": "Bank Account Added",
  "bankAccountRemoved": "Bank Account Removed",
  "YouDoNotHaveAnyBankAccountDetailsPleaseAddIt": "You don't have any bank \naccount details. Please add it.",
  "YourTicketHasBeenCreated": "Your ticket has been created. Please \ncheck the ticket details from\nSettings > Ticket Details",
  "unableToProcessYourRequest": "Unable To Process Your Request",
  "theWalletPointsTransferToYourBankAccountWasInitiatedSuccessfullyItMayTakeSometimesToReflectIntoAccount": "The wallet Points transfer to your bank account was initiated successfully.it may take sometimes to reflect into account.",
  "pleaseProvideCameraAccessToUseThisFeature": "Please provide camera access to use this feature",
  "noNetworkFound": "No network found, please check your network connections",
  "noResponse": "No response,Please try again after sometime",
  "networkConnections": "please check your network connections",
  "tryAfterSometime": "Try after sometime",
  "appUpdate": "App Update!",
  "updateTheApp": "App feature is changed, Please kindly update the app",
  "yourNetwork": "Please check your network",
  "accountNumberAlreadyExist": "Account Number is Already Exist",
  "YouHaveDisabledLocationAccessEarlier": "You have disabled the location access earlier. Please enable it again.",
  "bankTransferSubmitted": "Bank Transfer Submitted",
  "phoneNumberIsAlreadyRegistered": "This phone number is already registered and deleted by the user as requested. Do you want to reactivate it?",
  "invalidPhoneNumber": "Invalid phone number",
  "appPermission": "App Permission",
  "messageMustShouldNotBeEmpty": "Message must should not be empty",
  "totalRewardPoints": "Total Reward Points",
  "alreadyCouponScanned": "Already coupon scanned",
  "youAreLoggedOut": "Your are logged out",
  "invalidCouponCode": "Invalid Coupon Code!",
  "expiredCouponCode": "Expired Coupon Code!",
  "redeemYourGifts": "Redeem Your Gifts",
  "youWillBeRewarded": "You Will Be Rewarded",
  "makeYourBrandAuthentic": "Make Your Brand Authentic",
  "tutorial_1_content": "Customers / channel partners can now earn and redeem their rewards either through bank  transfer or Paytm almost instantly",
  "tutorial_2_content": "Loyalty Managemt can also be provided for original products, consumers / channel partners can now earn rewards for every product purchased.",
  "tutorial_3_content": "App is a product Authentication tool. Manufacturers can enable their Consumers to verify authenticity of their products."
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en};
}
