class Autogenerated {
  Data? data;
  String? status;

  Autogenerated({this.data, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['status'] = this.status;
    return data;
  }
}

class Data {
  String? appLink;
  int? notificationCount;
  bool? isKyc;
  Language? language;
  Consumer? consumer;

  Data(
      {this.appLink,
        this.notificationCount,
        this.isKyc,
        this.language,
        this.consumer});

  Data.fromJson(Map<String, dynamic> json) {
    appLink = json['appLink'];
    notificationCount = json['notificationCount'];
    isKyc = json['isKyc'];
    language = json['language'] != null
        ? new Language.fromJson(json['language'])
        : null;
    consumer = json['consumer'] != null
        ? new Consumer.fromJson(json['consumer'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['appLink'] = this.appLink;
    data['notificationCount'] = this.notificationCount;
    data['isKyc'] = this.isKyc;
    if (this.language != null) {
      data['language'] = this.language!.toJson();
    }
    if (this.consumer != null) {
      data['consumer'] = this.consumer!.toJson();
    }
    return data;
  }
}

class Language {
  int? languageId;
  String? languageName;
  String? languageJson;

  Language({this.languageId, this.languageName, this.languageJson});

  Language.fromJson(Map<String, dynamic> json) {
    languageId = json['languageId'];
    languageName = json['languageName'];
    languageJson = json['languageJson'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['languageId'] = this.languageId;
    data['languageName'] = this.languageName;
    data['languageJson'] = this.languageJson;
    return data;
  }
}

class Consumer {
  String? firstName;
  String? mobile;
  bool? isbanktermsverified;
  int? accBalance;
  String? email;

  Consumer(
      {this.firstName,
        this.mobile,
        this.isbanktermsverified,
        this.accBalance,
        this.email});

  Consumer.fromJson(Map<String, dynamic> json) {
    firstName = json['firstName'];
    mobile = json['mobile'];
    isbanktermsverified = json['isbanktermsverified'];
    accBalance = json['accBalance'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['firstName'] = this.firstName;
    data['mobile'] = this.mobile;
    data['isbanktermsverified'] = this.isbanktermsverified;
    data['accBalance'] = this.accBalance;
    data['email'] = this.email;
    return data;
  }
}